// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreFuels.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250301115845_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorizationProduct", b =>
                {
                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ProductsProductId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserProducts", (string)null);
                });

            modelBuilder.Entity("CoreFuels.ModelsEF.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("CoreFuels.ModelsEF.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Proteins")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Calories = "52",
                            Carbohydrates = 14.0,
                            Fats = 0.20000000000000001,
                            Name = "Apple",
                            Proteins = 0.29999999999999999
                        },
                        new
                        {
                            ProductId = 2,
                            Calories = "96",
                            Carbohydrates = 27.0,
                            Fats = 0.29999999999999999,
                            Name = "Banana",
                            Proteins = 1.3
                        },
                        new
                        {
                            ProductId = 3,
                            Calories = "165",
                            Carbohydrates = 0.0,
                            Fats = 3.6000000000000001,
                            Name = "Chicken Breast",
                            Proteins = 31.0
                        },
                        new
                        {
                            ProductId = 4,
                            Calories = "130",
                            Carbohydrates = 28.0,
                            Fats = 0.29999999999999999,
                            Name = "Rice",
                            Proteins = 2.7000000000000002
                        },
                        new
                        {
                            ProductId = 5,
                            Calories = "68",
                            Carbohydrates = 0.59999999999999998,
                            Fats = 4.7999999999999998,
                            Name = "Egg",
                            Proteins = 5.5
                        },
                        new
                        {
                            ProductId = 6,
                            Calories = "42",
                            Carbohydrates = 5.0,
                            Fats = 1.0,
                            Name = "Milk",
                            Proteins = 3.3999999999999999
                        },
                        new
                        {
                            ProductId = 7,
                            Calories = "265",
                            Carbohydrates = 49.0,
                            Fats = 3.2000000000000002,
                            Name = "Bread",
                            Proteins = 9.0
                        },
                        new
                        {
                            ProductId = 8,
                            Calories = "402",
                            Carbohydrates = 1.3,
                            Fats = 33.0,
                            Name = "Cheese",
                            Proteins = 25.0
                        },
                        new
                        {
                            ProductId = 9,
                            Calories = "18",
                            Carbohydrates = 3.8999999999999999,
                            Fats = 0.20000000000000001,
                            Name = "Tomato",
                            Proteins = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 10,
                            Calories = "77",
                            Carbohydrates = 17.0,
                            Fats = 0.10000000000000001,
                            Name = "Potato",
                            Proteins = 2.0
                        },
                        new
                        {
                            ProductId = 11,
                            Calories = "41",
                            Carbohydrates = 10.0,
                            Fats = 0.20000000000000001,
                            Name = "Carrot",
                            Proteins = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 12,
                            Calories = "47",
                            Carbohydrates = 12.0,
                            Fats = 0.10000000000000001,
                            Name = "Orange",
                            Proteins = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 13,
                            Calories = "250",
                            Carbohydrates = 0.0,
                            Fats = 15.0,
                            Name = "Beef",
                            Proteins = 26.0
                        },
                        new
                        {
                            ProductId = 14,
                            Calories = "208",
                            Carbohydrates = 0.0,
                            Fats = 13.0,
                            Name = "Fish (Salmon)",
                            Proteins = 20.0
                        },
                        new
                        {
                            ProductId = 15,
                            Calories = "59",
                            Carbohydrates = 3.6000000000000001,
                            Fats = 0.40000000000000002,
                            Name = "Yogurt",
                            Proteins = 10.0
                        },
                        new
                        {
                            ProductId = 16,
                            Calories = "50",
                            Carbohydrates = 13.0,
                            Fats = 0.10000000000000001,
                            Name = "Pineapple",
                            Proteins = 0.5
                        },
                        new
                        {
                            ProductId = 17,
                            Calories = "32",
                            Carbohydrates = 7.7000000000000002,
                            Fats = 0.29999999999999999,
                            Name = "Strawberry",
                            Proteins = 0.69999999999999996
                        },
                        new
                        {
                            ProductId = 18,
                            Calories = "131",
                            Carbohydrates = 25.0,
                            Fats = 1.1000000000000001,
                            Name = "Pasta",
                            Proteins = 5.0
                        },
                        new
                        {
                            ProductId = 19,
                            Calories = "717",
                            Carbohydrates = 0.10000000000000001,
                            Fats = 81.0,
                            Name = "Butter",
                            Proteins = 0.90000000000000002
                        },
                        new
                        {
                            ProductId = 20,
                            Calories = "15",
                            Carbohydrates = 2.8999999999999999,
                            Fats = 0.20000000000000001,
                            Name = "Lettuce",
                            Proteins = 1.3999999999999999
                        },
                        new
                        {
                            ProductId = 21,
                            Calories = "16",
                            Carbohydrates = 3.6000000000000001,
                            Fats = 0.10000000000000001,
                            Name = "Cucumber",
                            Proteins = 0.59999999999999998
                        },
                        new
                        {
                            ProductId = 22,
                            Calories = "304",
                            Carbohydrates = 82.400000000000006,
                            Fats = 0.0,
                            Name = "Honey",
                            Proteins = 0.29999999999999999
                        },
                        new
                        {
                            ProductId = 23,
                            Calories = "654",
                            Carbohydrates = 14.0,
                            Fats = 65.0,
                            Name = "Walnuts",
                            Proteins = 15.0
                        },
                        new
                        {
                            ProductId = 24,
                            Calories = "579",
                            Carbohydrates = 22.0,
                            Fats = 50.0,
                            Name = "Almonds",
                            Proteins = 21.0
                        },
                        new
                        {
                            ProductId = 25,
                            Calories = "546",
                            Carbohydrates = 61.0,
                            Fats = 31.0,
                            Name = "Chocolate",
                            Proteins = 7.0
                        },
                        new
                        {
                            ProductId = 26,
                            Calories = "22",
                            Carbohydrates = 3.2999999999999998,
                            Fats = 0.29999999999999999,
                            Name = "Mushrooms",
                            Proteins = 3.1000000000000001
                        },
                        new
                        {
                            ProductId = 27,
                            Calories = "588",
                            Carbohydrates = 20.0,
                            Fats = 50.0,
                            Name = "Peanut Butter",
                            Proteins = 25.0
                        },
                        new
                        {
                            ProductId = 28,
                            Calories = "160",
                            Carbohydrates = 9.0,
                            Fats = 15.0,
                            Name = "Avocado",
                            Proteins = 2.0
                        },
                        new
                        {
                            ProductId = 29,
                            Calories = "57",
                            Carbohydrates = 14.5,
                            Fats = 0.29999999999999999,
                            Name = "Blueberries",
                            Proteins = 0.69999999999999996
                        },
                        new
                        {
                            ProductId = 30,
                            Calories = "389",
                            Carbohydrates = 66.299999999999997,
                            Fats = 6.9000000000000004,
                            Name = "Oats",
                            Proteins = 16.899999999999999
                        },
                        new
                        {
                            ProductId = 31,
                            Calories = "23",
                            Carbohydrates = 3.6000000000000001,
                            Fats = 0.40000000000000002,
                            Name = "Spinach",
                            Proteins = 2.8999999999999999
                        },
                        new
                        {
                            ProductId = 32,
                            Calories = "354",
                            Carbohydrates = 15.199999999999999,
                            Fats = 33.5,
                            Name = "Coconut",
                            Proteins = 3.2999999999999998
                        },
                        new
                        {
                            ProductId = 33,
                            Calories = "69",
                            Carbohydrates = 18.100000000000001,
                            Fats = 0.20000000000000001,
                            Name = "Grapes",
                            Proteins = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("AuthorizationProduct", b =>
                {
                    b.HasOne("CoreFuels.ModelsEF.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreFuels.ModelsEF.Authorization", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
